In [1]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

from utility import load_mnist_images, load_mnist_labels, one_hot_encoding
from backpro import NN_model

In [2]:
train_images = load_mnist_images('train-images.idx3-ubyte')
train_labels = load_mnist_labels('train-labels.idx1-ubyte')
test_images = load_mnist_images('t10k-images.idx3-ubyte')
test_labels = load_mnist_labels('t10k-labels.idx1-ubyte')

#test_images = test_images[-2000:]
#test_labels = test_labels[-2000:]

'''
# Show A Image
plt.gray()
plt.imshow(train_images_ori[50])
plt.show()
'''

m_train = train_images.shape[0] # number of training data
m_test = test_images.shape[0] # number of test data

train_images = train_images.reshape(m_train, -1).T / 127.5 - 1
test_images = test_images.reshape(m_test, -1).T / 127.5 - 1

train_X = train_images
test_X = test_images
train_Y = one_hot_encoding(train_labels, 10)
test_Y = one_hot_encoding(test_labels, 10)

In [3]:
layers = [784, 64, 10]

model = NN_model(layers, 100)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0))

0 epoches cost: 0.201542
20 epoches cost: 0.102667
40 epoches cost: 0.007489
60 epoches cost: 0.004709
80 epoches cost: 0.006875
0.9689
[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 8 4]
[7 2 1 ..., 4 5 6]


In [4]:
layers = [784, 32, 32, 10]

model = NN_model(layers, 100)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0))

0 epoches cost: 0.442638
20 epoches cost: 0.059116
40 epoches cost: 0.054377
60 epoches cost: 0.082907
80 epoches cost: 0.034121
0.9566
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 8 4]
[7 2 1 ..., 4 5 6]


In [5]:
layers = [784, 300, 100, 10]

model = NN_model(layers, 100)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0))

0 epoches cost: 0.154603
20 epoches cost: 0.007028
40 epoches cost: 0.002690
60 epoches cost: 0.000060
80 epoches cost: 0.001013
0.9803
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 ..., 4 5 6]
