In [ ]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2
from utility import load_mnist_images, load_mnist_labels, one_hot_encoding, split_holdout, plot_cost_acc
from backpro import NN_model

In [29]:
train_images = load_mnist_images('train-images.idx3-ubyte',2000)
train_labels = load_mnist_labels('train-labels.idx1-ubyte',2000)
test_images = load_mnist_images('t10k-images.idx3-ubyte',200)
test_labels = load_mnist_labels('t10k-labels.idx1-ubyte',200)

#test_images = test_images[-2000:]
#test_labels = test_labels[-2000:]

'''
# Show A Image
plt.gray()
plt.imshow(train_images_ori[50])
plt.show()
'''

m_train = train_images.shape[0] # number of training data
m_test = test_images.shape[0] # number of test data



train_images = train_images.reshape(m_train, -1).T / 127.5 - 1
test_images = test_images.reshape(m_test, -1).T / 127.5 - 1


train_X = train_images
test_X = test_images

train_Y = one_hot_encoding(train_labels, 10)
test_Y = one_hot_encoding(test_labels, 10)

holdout_ratio = 0.1;
train_X, train_Y, holdout_X, holdout_Y = split_holdout(train_images, train_Y, holdout_ratio)

In [3]:
layers = [784, 64, 10]

model = NN_model(layers, 200)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0)[:20])

19 epoches cost: 0.081044
39 epoches cost: 0.042821
59 epoches cost: 0.030619
79 epoches cost: 0.040156
99 epoches cost: 0.012097
119 epoches cost: 0.008392
139 epoches cost: 0.007576
159 epoches cost: 0.003609
179 epoches cost: 0.004070
199 epoches cost: 0.002709
0.93
[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [ ]:
model.gradient_check(train_X, train_Y)

In [5]:
layers = [784, 32, 32, 10]

model = NN_model(layers, 100)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0)[:20])

19 epoches cost: 0.325830
39 epoches cost: 0.138207
59 epoches cost: 0.073568
79 epoches cost: 0.031884
99 epoches cost: 0.022301
0.925
[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [9]:
layers = [784, 48, 16, 10]

model = NN_model(layers, 100)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0)[:20])

19 epoches cost: 0.411289
39 epoches cost: 0.248137
59 epoches cost: 0.102516
79 epoches cost: 0.178045
99 epoches cost: 0.097466
0.88
[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [ ]:
layers = [784, 300, 100, 10]

model = NN_model(layers, 100)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0)[:20])

20 epoches cost: 0.101659
40 epoches cost: 0.013159
60 epoches cost: 0.005325
80 epoches cost: 0.003373


In [42]:
# holdout set + test set

layers = [784, 32, 32, 10]
model = NN_model(layers, 100, record=True)
train, val, test = model.fit(train_X, train_Y, holdout_X, holdout_Y, test_X, test_Y)
plot_cost_acc(train, val, test)

AttributeError: 'NN_model' object has no attribute 'record'