In [1]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2
from utility import load_mnist_images, load_mnist_labels, one_hot_encoding
from backpro import NN_model

In [2]:
train_images = load_mnist_images('train-images.idx3-ubyte',2000)
train_labels = load_mnist_labels('train-labels.idx1-ubyte',2000)
test_images = load_mnist_images('t10k-images.idx3-ubyte',200)
test_labels = load_mnist_labels('t10k-labels.idx1-ubyte',200)

#test_images = test_images[-2000:]
#test_labels = test_labels[-2000:]

'''
# Show A Image
plt.gray()
plt.imshow(train_images_ori[50])
plt.show()
'''

m_train = train_images.shape[0] # number of training data
m_test = test_images.shape[0] # number of test data

train_images = train_images.reshape(m_train, -1).T / 127.5 - 1
test_images = test_images.reshape(m_test, -1).T / 127.5 - 1

train_X = train_images
test_X = test_images
train_Y = one_hot_encoding(train_labels, 10)
test_Y = one_hot_encoding(test_labels, 10)

In [7]:
layers = [784, 64, 10]

model = NN_model(layers, 200)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0)[:20])

19 epoches cost: 0.136833
39 epoches cost: 0.038379
59 epoches cost: 0.030452
79 epoches cost: 0.025655
99 epoches cost: 0.013061
119 epoches cost: 0.009772
139 epoches cost: 0.010574
159 epoches cost: 0.005320
179 epoches cost: 0.002785
199 epoches cost: 0.003927
0.95
[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [8]:
model.gradient_check(train_X, train_Y)

0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00399025463747
0.00350149895247
0.00408121228696
0.00406687415399
0.00350908619492
0.00304528664511
0.00390059048249
0.003794603736
0.00385834547153
0.00406196873656
0.00408333110035
0.00408398996132
0.00408422063223
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443
0.00408424613443

0.00671461357705
0.00796677490258
0.00172729929236
-0.000936211950111
0.00450439956659
0.0011495121285
-0.00460823567401
0.0065768545116
0.00424536925117
0.00317006224927
0.0103379030605
-0.000304719423982
0.000394781412104
0.00285137254274
0.000610021968197
-0.000261332266638
0.00514545307478
0.00518579091923
0.00718733845575
0.00458823559089
0.00559091299083
0.00385308529205
0.00408486543969
0.00408424613443
0.00408424613443
0.00408515416581
0.00344835434846
0.00530055187629
0.00537083434938
0.00221530164837
-0.00241445659527
0.00375531198527
0.00325016755074
0.00131430728963
-0.00068848983694
0.00742454254846
0.00591513047994
0.00520145993119
0.00336306886485
-0.000522761562161
0.000394119593831
-0.0021988839792
-0.00130274517383
0.00234177529667
0.00631333724368
0.00522490770797
0.00609901212954
0.00469245996535
0.00453885344327
0.00400692115788
0.00435498057819
0.00408424613443
0.00408424613443
0.00462398954521
0.00448151662158
0.0019730845764
-0.00205077389981
0.00118656423547
-0

-0.00543601746012
-0.00171835861777
-0.00022776460703
-0.00605117841569
0.00118865611191
0.00402223227564
0.00820997719859
0.00550275945144
-8.21128660299e-05
0.00182863056526
0.00202732294638
0.00264795840319
0.00174582437328
0.00152350634517
0.00207189265366
0.00207277555267
0.0020660078872
0.00245962794882
0.00435658142118
0.00521697772467
0.00603337173468
0.00418704288366
-0.00104060883491
0.00454654867877
0.000691641340498
0.00236104382972
0.00302267940996
0.00612354449766
0.00120634397474
-0.00379951142814
-0.00730211516622
-0.00329727435126
0.00336890591879
0.00448511911939
0.00435742006536
0.00677039186079
0.00316590524515
0.000939512828086
0.00241698248534
0.00295985767739
0.0012774124924
0.00189852550874
0.00207153385256
0.00207138186059
0.0020668850304
0.00263009672488
0.00599384229138
0.00516309930368
0.00220970916017
-0.000851462215494
-0.00480402650718
-0.000497866155541
-0.0014108115915
-0.00198288881439
0.00537498630973
0.00322753430646
0.00381880605982
-0.0056089403189

0.00206516250751
0.00207200976219
0.00207200976219
0.00207200976219
0.00207200976219
0.00207200976219
0.00207200976219
0.0029398236358
0.00453778325424
0.00262049062264
-0.000426095141769
-0.000375707264541
-0.000200172064051
-0.0015526549075
-0.00233786998229
-0.00191666166837
0.00484034620772
0.00723105150657
0.00128163743471
-0.000927887574845
-0.00126718780241
0.00656443247785
0.00773448025925
0.00967044635354
0.00622423376884
0.00432505668147
0.00445373888913
0.00256191077968
0.00206886117643
0.00207200976219
0.00207200976219
0.00207200976219
0.00207200976219
0.00207200976219
0.00207200976219
0.00207292278592
0.00207872788665
0.00169056551134
0.00121150177723
0.000543169064737
0.00034842397384
-0.00103851323553
-0.00231755836097
0.00099605777081
0.00301417741519
-0.00136844800365
-0.0032867491517
0.000696075870892
0.00100299446891
0.00209217510348
0.00741756148702
0.00872244703981
0.00676113618407
0.00429231761599
0.0037221016811
0.00207226816917
0.00207243027141
0.00207200976219


0.000416799004189
-0.00869537958678
0.00200627803408
-0.00473422097387
0.00581228812215
0.00326353570658
0.00187763104263
0.00131868639551
-0.00532612723033
0.00120662596132
0.00622110095677
-0.00281938812575
-0.00118162724458
0.00377343064525
-0.00451137876742
-0.000337714859855
-0.000683062230951
-0.00108860078584
-0.000533742987362
-0.000533690559048
-0.000533690559048
-0.000553348722246
-0.00119282208412
-0.0037422444448
-0.0117187190186
-0.0100560277712
0.0064080962826
0.00393752357425
0.00106107805743
-0.0012024357975
-0.00236628614673
-0.00523024779478
2.38012409719e-05
-0.00412914507326
-0.00173209870783
0.0090282445466
0.0107020190143
-0.00598058355754
0.00454593286433
0.00183285268144
-0.00394862071525
-0.00557459934067
-0.00583866881076
-0.00140452941149
0.00051909393584
0.000654336475351
-0.000533696620116
-0.000533690559048
-0.000533690559048
-0.000533690559048
-0.000643425379273
-0.00358916308423
-0.00950513761552
-0.00767996058223
-0.000390231470883
0.0045023275134
-0.00

-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00696691376693
-0.00656653772357
-0.00703734101083
-0.00702759840459
-0.00691907837192
-0.00682295953279
-0.0070223110359
-0.00694230581105
-0.00687732170501
-0.00701052149145
-0.00704350513841
-0.00704375053961
-0.00704383964501
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00704390920067
-0.00703350774545
-0.00683736584777
-0.00666077936003
-0.00600128127534
-0.00563406375902
-0.00644545420731
-0.00661061659005
-0.00595069780627
-0.00699539089555
-0.00747790399974
-0.00475194206839
-0.0059573404366
-0.00672684905082
-0.0067975720815
-0.00664719941337
-0.00686494654636
-0.00704717599715
-0.00704538382423
-0.00704390920067
-0.00704390920067
-0.0070439092

-0.00325234582906
-0.0015713446596
-0.00478607882374
-0.00774213733862
-0.00865713960979
-0.00702050636983
-0.00662208133708
-0.00701465194159
-0.0070378648716
-0.00704390920067
-0.00704390920067
-0.00706324940306
-0.00613227538258
-0.00644529111724
-0.0082884407862
-0.00514749194044
-0.00403192295748
-0.0050942259447
8.99293271529e-05
0.000207972238708
1.08857426789e-05
0.00150525653504
0.00383240951045
-0.00318541606029
0.000268462291962
-0.00127865033197
-0.00357767921362
-0.00285313575999
-0.00455550492967
-0.00427232545213
-0.0053921496058
-0.00686454262801
-0.00698246906966
-0.00370968828289
-0.00688985271064
-0.00703483934055
-0.00772771613099
-0.00704390920067
-0.00704390920067
-0.00702356129403
-0.00603756663236
-0.00232730808546
-0.00179662370385
-0.00704535716637
-0.00608518585337
0.00143524273046
0.00047926062934
-0.00297576831838
-0.00187821784932
0.00762348612281
0.00787520952022
-0.00115970695153
-0.000320216304578
0.00171704938306
-0.00560355211954
-0.00407255227391
-0.

-0.00116371081945
-0.00736390721251
-0.00774493312232
-0.00698396952617
-0.00210200391654
-0.00435728798086
-0.00724537213827
-0.0115989000449
-0.00825954649968
-0.00550851205523
-0.00843075226192
-0.0152320884667
-0.0155212101878
-0.0142477229848
-0.0133221016775
-0.0146174522337
-0.0146193223463
-0.0146213597724
-0.013551571687
-0.0135728461189
-0.0124857649994
-0.011998256764
-0.0151323400664
-0.0124870007503
-0.0184115737304
-0.0096952532802
0.00195056065101
-0.00366145921384
-0.00986511519199
0.00149680303968
-0.00466179851683
-0.000810938728927
0.00264366028972
-0.00294831970336
-0.013682653816
-0.0134477650924
-0.0137486244885
-0.0112870258584
-0.0125466784534
-0.016502654504
-0.0139545891418
-0.0126567573332
-0.0141458565231
-0.0146265176625
-0.0146303578779
-0.0146303636259
-0.0138231454164
-0.0132745407092
-0.0151351087858
-0.0155771239818
-0.0170074563838
-0.0255669215188
-0.0202704222474
-0.0100667401202
-0.00824994148487
-0.014384249306
-0.00202304499845
0.00440541128896
0

KeyboardInterrupt: 

In [8]:
layers = [784, 32, 32, 10]

model = NN_model(layers, 100)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0)[:20])

19 epoches cost: 0.476499
39 epoches cost: 0.216357
59 epoches cost: 0.064431
79 epoches cost: 0.086313
99 epoches cost: 0.029717
0.9
[7 2 1 0 4 1 4 7 6 9 0 6 9 0 1 5 9 7 2 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [9]:
layers = [784, 48, 16, 10]

model = NN_model(layers, 100)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0)[:20])

19 epoches cost: 0.411289
39 epoches cost: 0.248137
59 epoches cost: 0.102516
79 epoches cost: 0.178045
99 epoches cost: 0.097466
0.88
[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [10]:
layers = [784, 300, 100, 10]

model = NN_model(layers, 100)
model.fit(train_X, train_Y)
model.predict(test_X, test_Y)
    
print(model.accuracy)
print(model.Y_p[:20])
print(np.argmax(test_Y, axis=0)[:20])

19 epoches cost: 0.033878
39 epoches cost: 0.008315
59 epoches cost: 0.003293
79 epoches cost: 0.003026
99 epoches cost: 0.001882
0.955
[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
